import '../models/models.dart';
import 'http.dart';
import 'marzban_api.dart';
import 'xui_api.dart';

/// Which set of client fields the user form shows.
enum UserFormKind { marzban, xuiLegacy, xuiV3 }

/// Common interface for all supported panels.
abstract class PanelApi {
  PanelApi(this.config);

  final PanelConfig config;

  /// Tests replace this to render screens against a fake panel.
  static PanelApi Function(PanelConfig config)? factoryOverride;

  static PanelApi create(PanelConfig config) =>
      factoryOverride?.call(config) ??
      (config.type == PanelType.marzban ? MarzbanApi(config) : XuiApi(config));

  bool get isMarzban => config.type == PanelType.marzban;

  /// True when one user can be attached to several inbounds at once
  /// (3X-UI 3.x client catalog). Valid after [prepare].
  bool get supportsMultiInbound => false;

  /// Field set for the user form. Valid after [prepare].
  UserFormKind get userFormKind;

  /// Inbound add/edit/delete is available.
  bool get canManageInbounds => false;

  /// Panel settings / Xray config editing is available.
  bool get hasPanelSettings => false;

  /// Detects panel capabilities before showing forms.
  Future<void> prepare() async {}

  /// Links generated by the panel itself, when it offers that; null if not.
  Future<List<String>?> fetchLinks(PanelUser user) async => null;

  Future<void> login();
  Future<ServerStats> status();
  Future<List<PanelUser>> users();
  Future<List<InboundInfo>> inbounds();
  Future<void> createUser(UserDraft draft);
  Future<void> updateUser(PanelUser user, UserDraft draft);
  Future<void> setEnabled(PanelUser user, bool enabled);
  Future<void> deleteUser(PanelUser user);
  Future<void> resetTraffic(PanelUser user);
  Future<void> restartCore();

  // Inbound management (x-ui only).
  Future<Map<String, dynamic>> rawInbound(int id) => _unsupported();
  Future<void> saveInbound(Map<String, dynamic> inbound, {int? id}) => _unsupported();
  Future<void> deleteInbound(int id) => _unsupported();
  Future<void> setInboundEnabled(int id, bool enabled) => _unsupported();
  Future<void> resetInboundTraffic(int id) => _unsupported();

  /// New X25519 key pair for Reality: (privateKey, publicKey).
  Future<(String, String)> newRealityKeys() => _unsupported();

  // Panel settings (x-ui only).
  Future<Map<String, dynamic>> panelSettings() => _unsupported();
  Future<void> savePanelSettings(Map<String, dynamic> settings) => _unsupported();
  Future<void> restartPanel() => _unsupported();
  Future<String> xrayConfig() => _unsupported();
  Future<void> saveXrayConfig(String json) => _unsupported();

  void dispose();

  Future<T> _unsupported<T>() =>
      Future.error(ApiException('Not supported by this panel.'));
}
