name: xui_manager
description: Manage 3X-UI, Alireza X-UI and Marzban panels from your phone.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: '>=9.2.2 <11.0.0'
  qr_flutter: ^4.1.0
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/icon.png
  adaptive_icon_background: '#23244A'
  adaptive_icon_foreground: assets/icon/icon_fg.png
