"""Patch the Android project generated by `flutter create` in CI.

- INTERNET permission + cleartext HTTP (many panels run on plain http)
- app label
- minSdk >= 23 (flutter_secure_storage)
- release signing from env (KEYSTORE_BASE64, KEYSTORE_PASSWORD, KEY_ALIAS,
  KEY_PASSWORD) when provided; otherwise the template's debug signing stays.
"""
import base64
import os
import pathlib
import re
import sys

APP_LABEL = "XUI Manager"
app = pathlib.Path("android/app")

manifest = app / "src/main/AndroidManifest.xml"
m = manifest.read_text(encoding="utf-8")
if "android.permission.INTERNET" not in m:
    m = m.replace(
        "<application",
        '<uses-permission android:name="android.permission.INTERNET"/>\n    <application',
        1,
    )
if "usesCleartextTraffic" not in m:
    m = m.replace("<application", '<application\n        android:usesCleartextTraffic="true"', 1)
m = re.sub(r'android:label="[^"]*"', f'android:label="{APP_LABEL}"', m, count=1)
manifest.write_text(m, encoding="utf-8")
print("Patched AndroidManifest.xml")

keystore = os.environ.get("KEYSTORE_BASE64", "").strip()
if keystore:
    (app / "upload.jks").write_bytes(base64.b64decode(keystore))

kts = app / "build.gradle.kts"
groovy = app / "build.gradle"
if kts.exists():
    g = kts.read_text(encoding="utf-8")
    g = re.sub(r"minSdk\s*=\s*flutter\.minSdkVersion", "minSdk = maxOf(flutter.minSdkVersion, 23)", g)
    if keystore:
        block = """signingConfigs {
        create("release") {
            storeFile = file("upload.jks")
            storePassword = System.getenv("KEYSTORE_PASSWORD")
            keyAlias = System.getenv("KEY_ALIAS")
            keyPassword = System.getenv("KEY_PASSWORD")?.takeIf { it.isNotEmpty() }
                ?: System.getenv("KEYSTORE_PASSWORD")
        }
    }

    buildTypes {"""
        g = re.sub(r"buildTypes\s*\{", block, g, count=1)
        g = g.replace('signingConfigs.getByName("debug")', 'signingConfigs.getByName("release")')
    kts.write_text(g, encoding="utf-8")
    print("Patched build.gradle.kts" + (" (release signing)" if keystore else ""))
elif groovy.exists():
    g = groovy.read_text(encoding="utf-8")
    g = re.sub(r"minSdkVersion\s+flutter\.minSdkVersion", "minSdkVersion Math.max(flutter.minSdkVersion, 23)", g)
    g = re.sub(r"minSdk\s*=\s*flutter\.minSdkVersion", "minSdk = Math.max(flutter.minSdkVersion, 23)", g)
    if keystore:
        block = """signingConfigs {
        release {
            storeFile file("upload.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD") ?: System.getenv("KEYSTORE_PASSWORD")
        }
    }

    buildTypes {"""
        g = re.sub(r"buildTypes\s*\{", block, g, count=1)
        g = g.replace("signingConfigs.debug", "signingConfigs.release")
    groovy.write_text(g, encoding="utf-8")
    print("Patched build.gradle" + (" (release signing)" if keystore else ""))
else:
    sys.exit("android/app build file not found")
