import 'package:flutter/material.dart';

import '../api/panel_api.dart';
import '../l10n.dart';
import '../models/models.dart';
import '../theme.dart';
import '../utils/format.dart';
import '../widgets/common.dart';
import '../widgets/soft.dart';
import 'user_form_screen.dart';

class UserDetailScreen extends StatefulWidget {
  const UserDetailScreen({super.key, required this.api, required this.user});

  final PanelApi api;
  final PanelUser user;

  @override
  State<UserDetailScreen> createState() => _UserDetailScreenState();
}

class _UserDetailScreenState extends State<UserDetailScreen> {
  late PanelUser _u = widget.user;
  bool _busy = false;
  List<String>? _serverLinks;

  @override
  void initState() {
    super.initState();
    _loadServerLinks();
  }

  /// Prefer links generated by the panel (3X-UI 3.x) over local ones.
  Future<void> _loadServerLinks() async {
    final links = await widget.api.fetchLinks(_u);
    if (mounted && links != null && links.isNotEmpty) setState(() => _serverLinks = links);
  }

  Future<void> _reload() async {
    final list = await widget.api.users();
    final found = list.where((e) => e.key == _u.key).firstOrNull;
    if (found != null && mounted) setState(() => _u = found);
    await _loadServerLinks();
  }

  Future<void> _run(Future<void> Function() op, {bool popAfter = false}) async {
    final s = S.of(context);
    setState(() => _busy = true);
    try {
      await op();
      if (!mounted) return;
      showSnack(context, s.t('done'));
      if (popAfter) {
        Navigator.pop(context);
        return;
      }
      await _reload();
    } catch (e) {
      if (mounted) showSnack(context, '$e', error: true);
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  Future<void> _edit() async {
    final ok = await Navigator.push<bool>(context,
        MaterialPageRoute(builder: (_) => UserFormScreen(api: widget.api, user: _u)));
    // The name (and therefore the key) may have changed; go back to the list.
    if (ok == true && mounted) Navigator.pop(context);
  }

  Future<void> _delete() async {
    final s = S.of(context);
    final ok = await confirmDialog(context,
        title: s.t('delete_user_q'),
        message: '${_u.name}\n${s.t('delete_user_msg')}',
        action: s.t('delete'),
        danger: true);
    if (ok) await _run(() => widget.api.deleteUser(_u), popAfter: true);
  }

  Future<void> _reset() async {
    final s = S.of(context);
    final ok = await confirmDialog(context,
        title: s.t('reset_traffic'), message: s.t('reset_traffic_q'), action: s.t('reset_traffic'));
    if (ok) await _run(() => widget.api.resetTraffic(_u));
  }

  @override
  Widget build(BuildContext context) {
    final s = S.of(context);
    final theme = Theme.of(context);
    final u = _u;
    final remaining = u.total > 0 ? (u.total - u.used).clamp(0, u.total) : null;
    final rows = <(String, String)>[
      (s.t('status'), s.status(u.status)),
      if (u.up > 0 || !widget.api.isMarzban) (s.t('upload'), fmtBytes(u.up)),
      if (u.up > 0 || !widget.api.isMarzban) (s.t('download'), fmtBytes(u.down)),
      (s.t('used'), fmtBytes(u.used)),
      (s.t('data_limit'), u.total > 0 ? fmtBytes(u.total) : s.t('unlimited')),
      if (remaining != null) (s.t('remaining'), fmtBytes(remaining)),
      (
        s.t('expiry'),
        u.expiryDaysAfterFirstUse != null
            ? fmtExpiry(u, s)
            : u.expiry == null
                ? s.t('unlimited')
                : '${fmtDate(u.expiry)}\n${fmtExpiry(u, s)}'
      ),
      if (u.limitIp != null) (s.t('ip_limit'), u.limitIp == 0 ? s.t('unlimited') : '${u.limitIp}'),
      if (u.inboundName != null) (s.t('inbound'), u.inboundName!),
      if ((u.protocol ?? '').isNotEmpty) (s.t('protocol'), u.protocol!),
      if (widget.api.isMarzban || u.lastOnline != null)
        (s.t('last_online'), u.lastOnline == null ? s.t('never') : fmtDate(u.lastOnline)),
      if ((u.note ?? '').isNotEmpty) (s.t('note'), u.note!),
    ];

    return Scaffold(
      appBar: AppBar(
        title: Text(u.name),
        actions: [
          IconButton(
              tooltip: s.t('edit'), icon: const Icon(Icons.edit_outlined), onPressed: _busy ? null : _edit),
          IconButton(
              tooltip: s.t('delete'),
              icon: const Icon(Icons.delete_outline),
              onPressed: _busy ? null : _delete),
        ],
        bottom: _busy
            ? const PreferredSize(
                preferredSize: Size.fromHeight(3), child: LinearProgressIndicator(minHeight: 3))
            : null,
      ),
      body: RefreshIndicator(
        onRefresh: _reload,
        child: ListView(
          padding: const EdgeInsets.all(12),
          children: [
            SoftBox(
              radius: 22,
              child: Padding(
                padding: EdgeInsets.zero,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        _Chip(text: s.status(u.status), color: statusColor(u.status)),
                        const SizedBox(width: 8),
                        if (u.online) _Chip(text: s.t('online'), color: okColor),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Text(fmtTraffic(u, s), style: theme.textTheme.titleLarge),
                    const SizedBox(height: 8),
                    ClipRRect(
                      borderRadius: BorderRadius.circular(4),
                      child: LinearProgressIndicator(
                        value: u.usage ?? 0,
                        minHeight: 8,
                        backgroundColor: theme.colorScheme.surfaceContainerHighest,
                        color: usageColor(u.usage),
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(fmtExpiry(u, s), style: theme.textTheme.bodyMedium),
                    const SizedBox(height: 12),
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children: [
                        FilledButton.tonalIcon(
                          onPressed: _busy ? null : () => _run(() => widget.api.setEnabled(u, !u.enabled)),
                          icon: Icon(u.enabled ? Icons.pause_circle_outline : Icons.play_circle_outline),
                          label: Text(u.enabled ? s.t('disable') : s.t('enable')),
                        ),
                        FilledButton.tonalIcon(
                          onPressed: _busy ? null : _reset,
                          icon: const Icon(Icons.restart_alt),
                          label: Text(s.t('reset_traffic')),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
            SoftBox(
              radius: 22,
              padding: const EdgeInsets.symmetric(vertical: 6),
              child: Column(
                children: [
                  for (final (label, value) in rows)
                    ListTile(
                      dense: true,
                      title: Text(label),
                      trailing: ConstrainedBox(
                        constraints: const BoxConstraints(maxWidth: 220),
                        child: Text(value,
                            textAlign: TextAlign.end,
                            style: const TextStyle(fontWeight: FontWeight.w600)),
                      ),
                    ),
                ],
              ),
            ),
            if (u.subUrl != null) ...[
              SectionTitle(s.t('subscription')),
              SoftBox(radius: 22, padding: EdgeInsets.zero, child: QrBox(data: u.subUrl!)),
            ],
            if ((_serverLinks ?? u.links).isNotEmpty) ...[
              SectionTitle(s.t('config_links')),
              for (final link in _serverLinks ?? u.links)
                Padding(
                  padding: const EdgeInsets.only(bottom: 12),
                  child: SoftBox(
                  radius: 20,
                  padding: EdgeInsets.zero,
                  child: ExpansionTile(
                    shape: const Border(),
                    collapsedShape: const Border(),
                    leading: const Icon(Icons.qr_code_2),
                    title: Text(_linkTitle(link), maxLines: 1, overflow: TextOverflow.ellipsis),
                    children: [QrBox(data: link)],
                  ),
                  ),
                ),
            ],
            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }

  static String _linkTitle(String link) {
    final i = link.indexOf('://');
    final scheme = i > 0 ? link.substring(0, i).toUpperCase() : 'LINK';
    final h = link.lastIndexOf('#');
    var name = '';
    if (h > 0) {
      try {
        name = Uri.decodeComponent(link.substring(h + 1));
      } catch (_) {
        name = link.substring(h + 1);
      }
    }
    return name.isEmpty ? scheme : '$scheme · $name';
  }
}

class _Chip extends StatelessWidget {
  const _Chip({required this.text, required this.color});

  final String text;
  final Color color;

  @override
  Widget build(BuildContext context) => Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
        decoration: BoxDecoration(
            color: color.withValues(alpha: 0.15), borderRadius: BorderRadius.circular(20)),
        child: Text(text, style: TextStyle(color: color, fontWeight: FontWeight.w600)),
      );
}
